---
title: "Title"
author: "Kenta Yoshida"
format:
  html:
    theme: sandstone
    toc: true
    toc-depth: 2
    code-fold: true
    code-tools: true
date: "`r Sys.Date()`"
---


```{r}
#| echo: false
#| output: asis
# Handle colored text outputs
options(crayon.enabled = TRUE)
old_hooks <-
  fansi::set_knit_hooks(knitr::knit_hooks,
                        which = c("output", "message", "error", "warning"))
```

```{r, setup}
#| echo: false
#| warning: false
#| message: false

library(tidyverse)
library(glue)
library(here)
library(corrplot)

theme_set(theme_linedraw(base_size = 12))
```

# Notes


# Import data

```{r}

```


# Section

```{r}
warning("warning")
message("message")
print("output")

pressure %>% 
  mutate(group = ifelse(temperature < 150, "group a", "group b")) %>% 
  ggplot(aes(temperature, pressure, color = group)) +
  geom_point() +
  facet_wrap(~group) +
  labs(title = "Example figure of how it looks like",
       subtitle = "with theme settings")

```


# Session info

```{r}
devtools::session_info()
```
